---

- hosts: localhost
  vars_files:
    - ssh_keys.yml
  vars:
    github_username: "Z-xus"
    dotfiles_repo: ".dotfiles"
  become: true
  become_user: zxus

  pre_tasks:
    - import_tasks: tasks/update.yml

  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/clone_dots.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/node.yml
