---

- hosts: localhost
  become: true
  become_user: zxus

  pre_tasks:
  - name: Update cache
    package:
      update_cache: true
    become: true
    become_user: root

  - name: Update keys
    package:
      name: archlinux-keyring
      state: latest
    become: true
    become_user: root

  tasks:

  - name: Check dotfiles dir already exists
    ansible.builtin.stat:
      path: ~/dots
    register: dotfiles_dir

  - name: Clone dotfiles
    ansible.builtin.git:
      repo: 'https://github.com/Z-xus/dots'
      dest: '~/'
    when: not dotfiles_dir.stat.exists


  - name: install zsh
    package: name=zsh

  - name: Change shell
    become: true
    user:
      name: zxus
      shell: /usr/bin/zsh

  - name: Source zsh
    shell: source ~/.zshrc
    args:
      executable: /bin/zsh

  - name: Install node
    pacman:
      name: ["nodejs", "npm"]
      state: present
    become: true
    become_user: root

  - name: Install node version manager
    npm:
      name: n
      global: yes
    become: true
    become_user: root

  - name: Node v20
    become: true
    become_user: root
    shell: /usr/bin/n 20
