---

- hosts: localhost
  become: true
  become_user: zxus

  pre_tasks:
    - import_tasks: tasks/pre_task.yml

  tasks:
  - import_tasks: tasks/clone_dots.yml
  - import_tasks: tasks/zsh.yml
  - import_tasks: tasks/node.yml
