- name: Check if yadm is installed
  ansible.builtin.package:
    name: yadm
    state: present
  become: true

- name: Check if yadm is initialized
  ansible.builtin.stat:
    path: ~/
  register: yadm_initialized

- name: Clone dotfiles repository with yadm
  command: yadm clone git@github.com:Z-xus/.dotfiles.git
  when: not yadm_initialized.stat.exists
  become: true
  become_user: zxus

- name: Update yadm submodules
  command: yadm submodule update --init --recursive
  become: true
  become_user: zxus
  when: yadm_initialized.stat.exists
