- name: Install node
  pacman:
    name: ["nodejs", "npm"]
    state: present
  become: true
  become_user: root

- name: Install node version manager
  npm:
    name: n
    global: yes
  become: true
  become_user: root

- name: Node v20
  become: true
  become_user: root
  shell: /usr/bin/n 20
