- name: Update cache
  package:
    update_cache: true
  become: true
  become_user: root
  tags:
  - update
  - dotfiles
  when: ansible_facts['os_family'] == "Archlinux"

- name: Update arch-keys
  package:
    name: archlinux-keyring
    state: latest
  become: true
  become_user: root
  tags:
  - update
  - dotfiles
  when: ansible_facts['os_family'] == "Archlinux"
